### ISSUE TITLE
Objects floating away

### ISSUE THREAD

**Issue by hexahigh** [EldinZenderink/ThiccSmoke#1]
Objects that are in water (Debris, boats and other stuff) just float away.
I quickly found out it has to do with the wind function even tho its off.
I have reinstalled the mod and teardown and it didnt fix it.
For now i will disable the mod and i hope you will be able to fix it soon.

Cheers, Simon

**Comment by EldinZenderink** [comment]
Not entirely sure if you were using the code from github or the actual mod from the workshop, but it has already been fixed on the workshop version for the last few days. (Just forgot to commit here, if you were using the github version). Please let me know if you run into any other issues. 

If the wind issues still persists, try toggling it on and off, maybe there is a some persistent storage issue, but once you toggle it is should be solved.
